package bettingauthoritiyAPI;


import ID.BettingRoundID;

/**
 *
 */
public class BetTokenAuthority implements IBetTokenAuthority {


    /**
     * return a BettingToken generated by this authority, based on the bettingRoundID.
     *
     * @param bettingRoundID
     * @return
     */
    @Override
    public BetToken getBetToken(BettingRoundID bettingRoundID){
        // create token
        BetToken bettingBetToken = new BetToken(bettingRoundID);
        // timestamp and log
        // NOT RELEVANT TO KNOW THIS

        // return token
        return bettingBetToken;
    }

    /**
     * Generates a trully random integer based on the BetToken
     * @param betToken
     * @return random integer
     */
    @Override
    public Integer getRandomInteger(BetToken betToken){
        // NOT RELEVANT TO KNOW THIS
        return null;  // DUMMY IMPLEMENTATION
    }
}
